---
name: BottleXP
version: 0.0.2
main: iRainDrop\BottleXP\Main
api: 5.0.0
src-namespace-prefix: iRainDrop\BottleXP

permissions:
  bottlexp.cmd:
    description: Allows users to use this command
    default: true
...
